# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20180620_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='diaCumple',
            field=models.CharField(default='2018/11/11', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='mesCumple',
            field=models.CharField(default='2018/11/11', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoScout',
            field=models.CharField(default='2018/11/11', max_length=100),
            preserve_default=False,
        ),
    ]
