# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_auto_20180620_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPrograma', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('materiales', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patrulla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPatrulla', models.CharField(max_length=100)),
                ('idTropaidPatrulla', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('diaFundacion', models.CharField(max_length=100)),
                ('mesFundacion', models.CharField(max_length=100)),
                ('anoFundacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPrograma', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tropa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTropa', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('diaFundacion', models.CharField(max_length=100)),
                ('mesFundacion', models.CharField(max_length=100)),
                ('anoFundacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='anoCumple',
            field=models.CharField(default='11/11/2018', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='11/11/2018', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='idPatrulla',
            field=models.CharField(default='11/11/2018', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(default='11/11/2018', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreApoderado',
            field=models.CharField(default='2018/11/11', max_length=100),
            preserve_default=False,
        ),
    ]
