# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0004_auto_20180620_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tropa',
            new_name='Seccion',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='idTropa',
            new_name='idSeccion',
        ),
        migrations.RemoveField(
            model_name='patrulla',
            name='idTropaidPatrulla',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='anoCumple',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='diaCumple',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mesCumple',
        ),
        migrations.AddField(
            model_name='patrulla',
            name='idSeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Seccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idSeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Seccion'),
        ),
        migrations.AlterField(
            model_name='lineaprograma',
            name='idPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Programa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idPatrulla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Patrulla'),
        ),
    ]
