# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0005_auto_20180620_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaprograma',
            old_name='idPrograma',
            new_name='Programa',
        ),
        migrations.RenameField(
            model_name='patrulla',
            old_name='idSeccion',
            new_name='Seccion',
        ),
        migrations.RemoveField(
            model_name='patrulla',
            name='idPatrulla',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='idPrograma',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='idSeccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idUsuario',
        ),
    ]
