# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0006_auto_20180620_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idPatrulla',
            new_name='Patrulla',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='idSeccion',
            new_name='Seccion',
        ),
    ]
