# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0007_auto_20180620_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaprograma',
            name='competencia',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
