# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0008_lineaprograma_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoScout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='patrulla',
            name='anoFundacion',
        ),
        migrations.RemoveField(
            model_name='patrulla',
            name='diaFundacion',
        ),
        migrations.RemoveField(
            model_name='patrulla',
            name='mesFundacion',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='anoFundacion',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='diaFundacion',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='mesFundacion',
        ),
        migrations.AddField(
            model_name='patrulla',
            name='fundacion',
            field=models.DateField(default='2018-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha',
            field=models.DateField(default='2018-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='fundacion',
            field=models.DateField(default='2018-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fundacion',
            field=models.DateField(default='2018-11-11'),
            preserve_default=False,
        ),
    ]
