# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0009_auto_20180621_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoScout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.tipoScout'),
        ),
    ]
