# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0010_auto_20180621_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
