# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0011_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoDirigente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoDirigente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.tipoDirigente'),
        ),
    ]
