# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0012_auto_20180621_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoBiblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('urlImagen', models.CharField(max_length=100)),
                ('urlArchivo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
