# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0016_auto_20180624_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
            ],
        ),
    ]
