# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0018_auto_20180624_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='body',
            field=models.CharField(max_length=100000),
        ),
    ]
