# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0022_auto_20180624_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fundacion',
            field=models.DateField(),
        ),
    ]
