# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0023_auto_20180624_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacimiento',
            field=models.DateField(default='2018-06-23'),
            preserve_default=False,
        ),
    ]
