# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0024_usuario_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nacimiento',
        ),
    ]
