# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0025_remove_usuario_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosApoderado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('telefono2', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('parentesco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPadres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePadre', models.CharField(max_length=100)),
                ('rutPadre', models.CharField(max_length=100)),
                ('telefonoPadre', models.CharField(max_length=100)),
                ('telefono2Padre', models.CharField(max_length=100)),
                ('fundacionPadre', models.DateField()),
                ('NombreMadre', models.CharField(max_length=100)),
                ('rutMadre', models.CharField(max_length=100)),
                ('telefonoMadre', models.CharField(max_length=100)),
                ('telefono2Madre', models.CharField(max_length=100)),
                ('fundacionMadre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='opcionAdversa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='opcionPresentaNoPresenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='opcionSiNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupoAnterior',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='vive',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospadres',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Usuario'),
        ),
        migrations.AddField(
            model_name='datosapoderado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Usuario'),
        ),
        migrations.AddField(
            model_name='datosapoderado',
            name='viveConEl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.opcionSiNo'),
        ),
    ]
