# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0026_auto_20180624_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosMedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonoEmergencia', models.CharField(max_length=100)),
                ('telefonoEmergencia2', models.CharField(max_length=100)),
                ('estatura', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('sistemaSalud', models.CharField(max_length=100)),
                ('grupoSanguineo', models.CharField(max_length=100)),
                ('factorRH', models.CharField(max_length=100)),
                ('varicela', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('sarampion', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('meringitis', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('rubeola', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('paperas', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('tifoidea', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('hepatitis', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('hanta', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('apendicitis', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('escarlinata', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('convulcion', models.BooleanField(choices=[(False, 'No ha padecido'), (True, 'Si ha padecido')])),
                ('parasetamol', models.BooleanField(choices=[(False, 'Sin reacci\xf3n Adversa'), (True, 'Con reacci\xf3n Adversa')])),
                ('ibuprofeno', models.BooleanField(choices=[(False, 'Sin reacci\xf3n Adversa'), (True, 'Con reacci\xf3n Adversa')])),
                ('clorfenamina', models.BooleanField(choices=[(False, 'Sin reacci\xf3n Adversa'), (True, 'Con reacci\xf3n Adversa')])),
                ('loratadina', models.BooleanField(choices=[(False, 'Sin reacci\xf3n Adversa'), (True, 'Con reacci\xf3n Adversa')])),
                ('viadil', models.BooleanField(choices=[(False, 'Sin reacci\xf3n Adversa'), (True, 'Con reacci\xf3n Adversa')])),
                ('amoxisilina', models.BooleanField(choices=[(False, 'Sin reacci\xf3n Adversa'), (True, 'Con reacci\xf3n Adversa')])),
                ('alergiaAlimentaria', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('alergiaMedicamento', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('alergiaOtros', models.CharField(max_length=1000)),
                ('utilizaLentes', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('esguince', models.BooleanField(choices=[(False, 'No ha presentado'), (True, 'Si ha presentado')])),
                ('fractura', models.BooleanField(choices=[(False, 'No ha presentado'), (True, 'Si ha presentado')])),
                ('operado', models.BooleanField(choices=[(False, 'No ha presentado'), (True, 'Si ha presentado')])),
                ('columna', models.BooleanField(choices=[(False, 'No ha presentado'), (True, 'Si ha presentado')])),
                ('piePlano', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('pieAtleta', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('movilidadReducida', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('hernias', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('diabetes', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('hipertension', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('epilepsia', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('asma', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('insuficienciaRenal', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('insifucienciaCardiaca', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('anemia', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('obesidad', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('apetito', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('reflujo', models.BooleanField(choices=[(False, 'No Presenta'), (True, 'Si Presenta')])),
                ('otra', models.CharField(max_length=100)),
                ('otra2', models.CharField(max_length=100)),
                ('otra3', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='opcionAdversa',
        ),
        migrations.DeleteModel(
            name='opcionPresentaNoPresenta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vive',
        ),
        migrations.AlterField(
            model_name='datosapoderado',
            name='viveConEl',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')]),
        ),
        migrations.DeleteModel(
            name='opcionSiNo',
        ),
    ]
