# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0029_auto_20180625_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('suceso', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(max_length=10000)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Usuario')),
            ],
        ),
    ]
