# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0032_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='asistencia',
            field=models.ManyToManyField(to='boletin.Asistencia'),
        ),
    ]
