# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0034_auto_20180626_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebaviews',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pruebas',
            field=models.ManyToManyField(to='boletin.PruebaViews'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='descripcion',
            field=models.CharField(max_length=10000),
        ),
    ]
