# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0035_auto_20180626_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pruebas',
            field=models.ManyToManyField(to='boletin.Prueba'),
        ),
    ]
