# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0037_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaprograma',
            name='competencia',
        ),
    ]
