# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0038_remove_lineaprograma_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='total',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
