# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0041_remove_puntaje_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='asistencia',
        ),
    ]
