# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0043_asistencia_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombreApoderado',
        ),
    ]
