# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0044_remove_usuario_nombreapoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
