# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0045_remove_usuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordNueva', models.CharField(max_length=15)),
                ('passwordAntigua', models.CharField(max_length=15)),
            ],
        ),
    ]
