# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0046_passwordfalse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebaviews',
            name='etapa',
        ),
        migrations.AddField(
            model_name='passwordfalse',
            name='passwordNueva2',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
