# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0049_auto_20180628_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoJefe',
            new_name='tipoDirigente',
        ),
    ]
