# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0053_patrulla_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.GrupoScout'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='system',
            field=models.BooleanField(choices=[(False, 'no'), (True, 'si')], default='0'),
            preserve_default=False,
        ),
    ]
