# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0054_auto_20180628_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='system',
        ),
    ]
