# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0055_remove_noticia_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivelNacional',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default='0'),
            preserve_default=False,
        ),
    ]
