# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0056_usuario_nivelnacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='nivelCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
