# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0057_nivelcuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nivelNacional',
        ),
    ]
