# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0059_usuario_nivelcuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoScoutFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('nombreJefe', models.CharField(max_length=100)),
                ('rutJefe', models.CharField(max_length=100)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boletin.Localidad')),
            ],
        ),
    ]
